[tool.poetry]
name = "Jiyu-replay-attack"
version = "3.0.0"
description = "Send packets to student machines disguised as Jiyu teacher machine"
authors = ["weilycoder <weily2009@outlook.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4"
scapy = "^2.6.1"
psutil = "^5.9.8"

[tool.poetry.dev-dependencies]
black = "^24.8.0"

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
